// Generates the standalone site from the single page source (index.html):
//  - public/index.html: the page wrapped in a full HTML document
//  - netlify/lib/rules.mjs: the agent instructions, so the server owns the system prompt
//  - public/manifest.webmanifest, sw.js, icons/: copied from static/ (installable app)
import { readFileSync, writeFileSync, mkdirSync, cpSync } from "node:fs";

const page = readFileSync(new URL("./index.html", import.meta.url), "utf8");

const m = page.match(/const RULES = `([\s\S]*?)`;/);
if (!m) throw new Error("RULES not found in index.html");
mkdirSync(new URL("./netlify/lib/", import.meta.url), { recursive: true });
writeFileSync(new URL("./netlify/lib/rules.mjs", import.meta.url),
  `// Generated by build.mjs from index.html — do not edit by hand.\nexport const RULES = ${JSON.stringify(m[1])};\n`);

const head = '<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">'
  + '<link rel="manifest" href="/manifest.webmanifest"><meta name="theme-color" content="#7A1F45"><link rel="icon" href="/icons/icon-192.png">'
  + '<link rel="apple-touch-icon" href="/icons/apple-touch-icon.png"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="Intake DSI">'
  + '<style>:root{color-scheme:light;padding-top:env(safe-area-inset-top,0px);padding-bottom:env(safe-area-inset-bottom,0px)}body{margin:0}img{max-width:100%}[hidden]{display:none!important}</style>'
  + '</head><body>';
mkdirSync(new URL("./public/", import.meta.url), { recursive: true });
writeFileSync(new URL("./public/index.html", import.meta.url), head + page + "</body></html>\n");
// Installable app: manifest, service worker and icons.
cpSync(new URL("./static/", import.meta.url), new URL("./public/", import.meta.url), { recursive: true });
console.log("built public/index.html and netlify/lib/rules.mjs");
